"""activities and competitions module

Revision ID: 30dddfac33a7
Revises: d00795589ad7
Create Date: 2026-09-15 14:54:00.082694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dddfac33a7'
down_revision: Union[str, None] = 'd00795589ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'student_id', name='uq_activity_participant')
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO school_modules (school_id, module_key, enabled)
        SELECT id, 'activities', true FROM schools
        WHERE NOT EXISTS (
            SELECT 1 FROM school_modules
            WHERE school_modules.school_id = schools.id AND school_modules.module_key = 'activities'
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM school_modules WHERE module_key = 'activities'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_participants')
    op.drop_table('activities')
    # ### end Alembic commands ###
