"""transport module and mpesa payments

Revision ID: 3c97176265aa
Revises: f0a2d4ba3568
Create Date: 2026-09-15 13:54:41.541019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c97176265aa'
down_revision: Union[str, None] = 'f0a2d4ba3568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_payment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('mpesa_shortcode', sa.String(length=20), nullable=False),
    sa.Column('mpesa_consumer_key', sa.String(length=255), nullable=False),
    sa.Column('mpesa_consumer_secret_encrypted', sa.String(length=500), nullable=False),
    sa.Column('mpesa_passkey_encrypted', sa.String(length=500), nullable=False),
    sa.Column('mpesa_env', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('driver_phone', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'registration_number', name='uq_vehicle_registration')
    )
    op.create_table('transport_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_transport_route_name')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('merchant_reference', sa.String(length=100), nullable=False),
    sa.Column('order_tracking_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymenttransactionstatus'), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('initiated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_merchant_reference'), 'payment_transactions', ['merchant_reference'], unique=True)
    op.add_column(
        'fee_invoices',
        sa.Column('category', sa.String(length=30), nullable=False, server_default='tuition'),
    )
    op.alter_column('fee_invoices', 'category', server_default=None)
    op.add_column('students', sa.Column('transport_route_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('transport_stop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'transport_routes', ['transport_route_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'route_stops', ['transport_stop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Data migration: give every existing school the new "transport" module,
    # enabled by default — same as onboarding seeds it for new schools.
    op.execute(
        """
        INSERT INTO school_modules (school_id, module_key, enabled)
        SELECT id, 'transport', true FROM schools
        WHERE NOT EXISTS (
            SELECT 1 FROM school_modules
            WHERE school_modules.school_id = schools.id AND school_modules.module_key = 'transport'
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM school_modules WHERE module_key = 'transport'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'transport_stop_id')
    op.drop_column('students', 'transport_route_id')
    op.drop_column('fee_invoices', 'category')
    op.drop_index(op.f('ix_payment_transactions_merchant_reference'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_table('route_stops')
    op.drop_table('transport_routes')
    op.drop_table('vehicles')
    op.drop_table('school_payment_configs')
    # ### end Alembic commands ###
