"""school events on announcements

Revision ID: 3cf25d449c65
Revises: 30dddfac33a7
Create Date: 2026-09-15 15:00:36.125098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf25d449c65'
down_revision: Union[str, None] = '30dddfac33a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('announcements', sa.Column('event_end_date', sa.Date(), nullable=True))
    op.add_column('announcements', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'location')
    op.drop_column('announcements', 'event_end_date')
    op.drop_column('announcements', 'event_date')
    # ### end Alembic commands ###
