"""flutterwave card payments and optional mpesa fields

Revision ID: 52d328093805
Revises: 3c97176265aa
Create Date: 2026-09-15 14:24:25.937745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d328093805'
down_revision: Union[str, None] = '3c97176265aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_payment_configs', sa.Column('flutterwave_public_key', sa.String(length=255), nullable=True))
    op.add_column('school_payment_configs', sa.Column('flutterwave_secret_key_encrypted', sa.String(length=500), nullable=True))
    op.alter_column('school_payment_configs', 'mpesa_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('school_payment_configs', 'mpesa_consumer_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('school_payment_configs', 'mpesa_consumer_secret_encrypted',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('school_payment_configs', 'mpesa_passkey_encrypted',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school_payment_configs', 'mpesa_passkey_encrypted',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('school_payment_configs', 'mpesa_consumer_secret_encrypted',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('school_payment_configs', 'mpesa_consumer_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('school_payment_configs', 'mpesa_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('school_payment_configs', 'flutterwave_secret_key_encrypted')
    op.drop_column('school_payment_configs', 'flutterwave_public_key')
    # ### end Alembic commands ###
