"""meals module

Revision ID: 570273652e25
Revises: 52d328093805
Create Date: 2026-09-15 14:37:18.599161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570273652e25'
down_revision: Union[str, None] = '52d328093805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'date', 'meal_type', name='uq_meal_menu_slot')
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO school_modules (school_id, module_key, enabled)
        SELECT id, 'meals', true FROM schools
        WHERE NOT EXISTS (
            SELECT 1 FROM school_modules
            WHERE school_modules.school_id = schools.id AND school_modules.module_key = 'meals'
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM school_modules WHERE module_key = 'meals'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_menus')
    # ### end Alembic commands ###
