"""multi-branch schools

Revision ID: 6075fa33338f
Revises: 4f96db25382f
Create Date: 2026-09-15 15:27:04.954854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6075fa33338f'
down_revision: Union[str, None] = '4f96db25382f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('parent_school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schools', 'schools', ['parent_school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'parent_school_id')
    # ### end Alembic commands ###
