"""finance module

Revision ID: b631da451e0b
Revises: 3cf25d449c65
Create Date: 2026-09-15 15:12:46.226758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b631da451e0b'
down_revision: Union[str, None] = '3cf25d449c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO school_modules (school_id, module_key, enabled)
        SELECT id, 'finance', true FROM schools
        WHERE NOT EXISTS (
            SELECT 1 FROM school_modules
            WHERE school_modules.school_id = schools.id AND school_modules.module_key = 'finance'
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM school_modules WHERE module_key = 'finance'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
