"""subscription plans

Revision ID: c59b853b2be5
Revises: febfd62137a2
Create Date: 2026-09-15 21:49:18.324107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c59b853b2be5'
down_revision: Union[str, None] = 'febfd62137a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    sa.Enum('MONTHLY', 'ANNUAL', name='billingperiod').create(bind, checkfirst=True)
    sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', name='subscriptionstatus').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_period', postgresql.ENUM('MONTHLY', 'ANNUAL', name='billingperiod', create_type=False), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schools', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column(
        'schools',
        sa.Column(
            'subscription_status',
            postgresql.ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', name='subscriptionstatus', create_type=False),
            server_default='ACTIVE',  # existing schools already in production use — don't trial-gate them
            nullable=False,
        ),
    )
    op.alter_column('schools', 'subscription_status', server_default=None)
    op.add_column(
        'schools',
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '14 days'"), nullable=False),
    )
    op.alter_column('schools', 'trial_ends_at', server_default=None)
    op.create_foreign_key(None, 'schools', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_column('schools', 'trial_ends_at')
    op.drop_column('schools', 'subscription_status')
    op.drop_column('schools', 'plan_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
