"""student and guardian portal accounts

Revision ID: d10feb86c20e
Revises: c41244968d39
Create Date: 2026-09-12 08:34:33.964013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10feb86c20e'
down_revision: Union[str, None] = 'c41244968d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('guardian_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'users', ['guardian_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'guardian_user_id')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###
