"""lesson plans

Revision ID: d1baaf8b39a2
Revises: 07a9d22321a8
Create Date: 2026-10-06 13:38:43.146428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd1baaf8b39a2'
down_revision: Union[str, None] = '07a9d22321a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    sa.Enum('PLANNED', 'COMPLETED', name='lessonplanentrystatus').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_id', 'subject_id', 'term', name='uq_lesson_plan_scope')
    )
    op.create_table('lesson_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_plan_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'COMPLETED', name='lessonplanentrystatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO school_modules (school_id, module_key, enabled)
        SELECT id, 'lesson_plans', true FROM schools
        WHERE NOT EXISTS (
            SELECT 1 FROM school_modules
            WHERE school_modules.school_id = schools.id AND school_modules.module_key = 'lesson_plans'
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM school_modules WHERE module_key = 'lesson_plans'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_plan_entries')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
