"""switch card payments from flutterwave to pesapal

Revision ID: febfd62137a2
Revises: dbf4f8531684
Create Date: 2026-09-15 16:49:50.118237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febfd62137a2'
down_revision: Union[str, None] = 'dbf4f8531684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_payment_configs', sa.Column('pesapal_consumer_key', sa.String(length=255), nullable=True))
    op.add_column('school_payment_configs', sa.Column('pesapal_consumer_secret_encrypted', sa.String(length=500), nullable=True))
    op.add_column('school_payment_configs', sa.Column('pesapal_ipn_id', sa.String(length=100), nullable=True))
    op.add_column('school_payment_configs', sa.Column('pesapal_env', sa.String(length=20), server_default='sandbox', nullable=False))
    op.alter_column('school_payment_configs', 'pesapal_env', server_default=None)
    op.drop_column('school_payment_configs', 'flutterwave_secret_key_encrypted')
    op.drop_column('school_payment_configs', 'flutterwave_public_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_payment_configs', sa.Column('flutterwave_public_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('school_payment_configs', sa.Column('flutterwave_secret_key_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('school_payment_configs', 'pesapal_env')
    op.drop_column('school_payment_configs', 'pesapal_ipn_id')
    op.drop_column('school_payment_configs', 'pesapal_consumer_secret_encrypted')
    op.drop_column('school_payment_configs', 'pesapal_consumer_key')
    # ### end Alembic commands ###
